from typing import List, Dict, Optional, Literal
from pydantic import BaseModel, Field, field_validator

# --------------------------------------------------
# FOUNDER & TEAM PROFILE
# --------------------------------------------------
class FounderProfile(BaseModel):
    name: str = Field(description="Full name of the founder")
    role: str = Field(description="Role or title in the startup (e.g., CEO, CTO)")
    domain_experience_years: Optional[int] = Field(None, description="Years of professional experience in the startup domain")
    prior_exits: Optional[int] = Field(None, description="Number of prior company exits (M&A or IPO)")
    technical_expertise: Optional[str] = Field(None, description="Primary technical skills or specialized certifications")

# --------------------------------------------------
# RAW STARTUP INPUT INGESTION SCHEMA
# --------------------------------------------------
class RawStartupInput(BaseModel):
    name: str = Field(description="Name of the startup company")
    sector: str = Field(description="Industry sector (e.g., B2B SaaS, Fintech, DeepTech)")
    current_stage: Literal["Pre-seed", "Seed", "Series A"] = Field(description="Current investment or maturity stage")
    location: str = Field(description="Primary geographic headquarters")
    problem_statement: str = Field(description="The core problem the startup solves")
    solution_overview: str = Field(description="The startup's product/service solution overview")
    tech_stack_differentiation: str = Field(description="Proprietary technology stack and unique defensibility details")
    
    # Financials & Metrics (Optional for Pre-seed, heavily penalized in Series A if missing)
    tam_usd: Optional[float] = Field(None, description="Total Addressable Market in USD")
    sam_usd: Optional[float] = Field(None, description="Serviceable Addressable Market in USD")
    som_usd: Optional[float] = Field(None, description="Serviceable Obtainable Market in USD")
    mrr_usd: Optional[float] = Field(None, description="Monthly Recurring Revenue in USD")
    gross_margins_percent: Optional[float] = Field(None, description="Gross profit margins as a percentage")
    yoy_growth_percent: Optional[float] = Field(None, description="Year-over-Year revenue/user growth percentage")
    active_users: Optional[int] = Field(None, description="Number of monthly/daily active users or customers")
    
    # Team
    founders: List[FounderProfile] = Field(default=[], description="Profiles of the co-founders")
    
    # Market & Competition
    competitors: List[str] = Field(default=[], description="List of direct and indirect competitors")
    perceived_defensibility: str = Field(description="Founder's explanation of their competitive advantage/moat")
    known_risks: List[str] = Field(default=[], description="Identified execution, market, or operational risks")

# --------------------------------------------------
# QUANTIFIED EVALUATION DIMENSIONS
# --------------------------------------------------
class DimensionMetric(BaseModel):
    qualitative_score: float = Field(description="Raw qualitative score generated by LLM, clamped (1.0 to 10.0)")
    weighted_score: float = Field(description="Calculated weighted score based on startup maturity stage")
    reasoning: str = Field(description="Detailed rational explanation for the assigned score")
    evidence: List[str] = Field(description="Empirical data/quotes from the raw profile used as evidence")
    limitations: List[str] = Field(description="Missing metrics or unverified assertions related to this dimension")

# --------------------------------------------------
# RISK ANALYSIS STRUCTURE
# --------------------------------------------------
class RiskItem(BaseModel):
    risk_type: Literal["Operational", "Business/Financial", "Market/Competitive", "Regulatory/Legal", "Execution"] = Field(
        description="Categorization of the identified risk"
    )
    severity: Literal["High", "Medium", "Low"] = Field(description="Risk impact assessment")
    description: str = Field(description="Explanation of the threat and potential business impact")
    mitigation: str = Field(description="Actionable suggestion or strategy to mitigate the risk")

# --------------------------------------------------
# INTERMEDIATE LLM SYNTHESIS OUTPUT SCHEMA
# --------------------------------------------------
# Represents the raw structural response we instruct the Groq API to return.
class LLMQualitativeOutput(BaseModel):
    dimension_scores: Dict[str, float] = Field(
        description="Raw qualitative scores (1.0 - 10.0) for the 7 evaluation dimensions"
    )
    dimension_reasonings: Dict[str, str] = Field(
        description="Reasonings explaining each dimension score"
    )
    dimension_evidences: Dict[str, List[str]] = Field(
        description="Direct observations or data from the raw profile backing each dimension score"
    )
    dimension_limitations: Dict[str, List[str]] = Field(
        description="Unverified or missing data points flagged during analysis for each dimension"
    )
    risk_registry: List[RiskItem] = Field(
        description="Structured list of identified risks across categories"
    )
    strengths: List[str] = Field(description="Core strengths and unfair advantages identified")
    weaknesses: List[str] = Field(description="Core structural or execution weaknesses identified")
    due_diligence_questions: List[str] = Field(
        description="Targeted questions for founders to resolve gaps and unverified items"
    )
    recommendations: List[str] = Field(
        description="Strategic recommendations to improve startup metrics and investment readiness"
    )

    @field_validator("dimension_scores")
    @classmethod
    def validate_dimensions(cls, v: Dict[str, float]) -> Dict[str, float]:
        required = {
            "innovation_defensibility",
            "market_potential",
            "scalability",
            "revenue_viability",
            "founder_capability",
            "competition_risk",
            "funding_readiness"
        }
        missing = required - set(v.keys())
        if missing:
            raise ValueError(f"LLM output is missing required scoring dimensions: {missing}")
        
        # Clamp scores deterministic sanity check (1.0 to 10.0)
        clamped = {}
        for k, score in v.items():
            clamped[k] = max(1.0, min(10.0, float(score)))
        return clamped

# --------------------------------------------------
# FINAL UNIVERSAL VENTURE REPORT (downstream consumer)
# --------------------------------------------------
class UniversalVentureReport(BaseModel):
    startup_name: str = Field(description="Name of the startup evaluated")
    stage: str = Field(description="Stage under which evaluation was weighed")
    overall_score: float = Field(description="Final stage-weighted score minus risk penalties, normalized (1.0 - 10.0)")
    confidence_score: float = Field(description="Empirical completeness score of the startup profile (1.0 - 10.0)")
    dimension_scores: Dict[str, DimensionMetric] = Field(
        description="Comprehensive analysis metrics for each of the 7 core dimensions"
    )
    risk_registry: List[RiskItem] = Field(
        description="Categorized registry of startup operational and business risks"
    )
    strengths: List[str] = Field(description="Top key strengths identified by the engine")
    weaknesses: List[str] = Field(description="Top critical weaknesses flagged by the engine")
    due_diligence_questions: List[str] = Field(
        description="Targeted screening questions to resolve unverified claims"
    )
    recommendations: List[str] = Field(
        description="Strategic, evidence-driven actions to take next"
    )
